package page;

import constants.IlabJobPageElements;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import util.BasePageUtil;

import java.io.IOException;
import java.util.Random;

public class IlabJobPage extends BasePageUtil implements IlabJobPageElements {


    public IlabJobPage(WebDriver driver) throws IOException {
        super(driver);
    }


    public IlabCareerHomePage IlabJobPage(String Name,String Email) throws IOException {

        findElementFromListAndClick(FirstjobontheList,1);
        find(ApplyOnline).click();
        setText(name,Name);
        setText(txtEmail,Email);
        setText(phone,AutogeneratedPhoneNumber());
        find(btnSend).click();
        Assert.assertTrue(ValidText.equals(getText(text)));
        return new IlabCareerHomePage(driver);

    }




    public String AutogeneratedPhoneNumber() {
        Random generator = new Random();
        String firstdigit = new Integer(0).toString();
        String secondigit = new Integer(generator.nextInt(3) + 6).toString();
        String firstset = new Integer(generator.nextInt(8999) + 1000).toString();
        String secondset = new Integer(generator.nextInt(8999) + 1000).toString();

        String number = firstdigit + secondigit + firstset + secondset;
        return (number);
    }
}
