package constants;

import org.openqa.selenium.By;

public interface IlabJobPageElements extends General_Constants{


    public By txtEmail = By.id("email");
    public By name = By.id("applicant_name");
    public By phone = By.id("phone");
    public By btnSend = By.id("wpjb_submit");
    public By text = By.xpath("//span[@class='wpjb-glyphs wpjb-icon-attention']");
    public By FirstjobontheList = By.linkText("Software Test Engineer - Johannesburg");
    public By ApplyOnline = By.linkText("Apply Online");
    public  String AutogeneratedPhoneNumber();
}
